color: true
recursive: true
reporter: spec
require-main:
  - "test/support/main"
require:
  - "test/support/babel"
  - "test/support/coverage"
  - "test/support/mode"
  - "test/support/log"
  - "test/support/src"
  - "test/support/chai"
  - "test/support/args"
  - "test/support/fixtures"
slow: 250
