name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ${ matrix.os }

    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - os: ubuntu-latest
            friendlyName: Linux

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install and build dependencies
        run: npm install --no-progress --silent

      - name: Rebuild native dependencies for Electron
        run: npm run rebuild

      - name: Lint
        run: npm run lint

      - name: Create production bundle
        run: npm run rollup

      - name: Run main/renderer tests
        if: matrix.os != 'ubuntu-latest'
        run: npm test

      - name: Run main/renderer tests with coverage report
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run npm run coverage

      - name: Send coverage report to Coveralls
        if: matrix.os == 'ubuntu-latest'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
